# NUmpy Tutorial


In [1]:
import numpy as np

In [2]:
arr = np.array([10,30,25,67])

In [3]:
arr

array([10, 30, 25, 67])

In [4]:
arr = np.array([10,30,25,67])

In [5]:
arr[0] #if one d array

10

In [6]:
arr.shape

(4,)

In [7]:
arr.dtype

dtype('int64')

In [8]:
arr[0]

10

In [9]:
arr[0] = 29

In [10]:
arr

array([29, 30, 25, 67])

# ConVersion From other python structure

In [11]:
arr1 = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [12]:
arr1.shape

(3, 3)

In [13]:
arr1.dtype

dtype('int64')

In [14]:
arr1

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [15]:
arr1[1,0]

40

# Creating differrent array from python build in structre

In [16]:
zero = np.zeros((3,2))

In [17]:
zero

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [18]:
rnge = np.arange(5)

In [19]:
rnge

array([0, 1, 2, 3, 4])

In [20]:
lspace = np.linspace(10,50,10)

In [21]:
lspace

array([10.        , 14.44444444, 18.88888889, 23.33333333, 27.77777778,
       32.22222222, 36.66666667, 41.11111111, 45.55555556, 50.        ])

In [22]:
arr2 = np.arange(16)

In [23]:
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
arr2 = arr2.reshape(4,4)

In [25]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [26]:
arr2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
arr2.shape

(4, 4)

In [28]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [29]:
ar = np.array(x)

In [30]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
ar.sum(axis=0) #gives sum of all elements in column(0,0)+(1,1)+(2,2)(etc)...

array([12, 15, 18])

In [32]:
ar.sum(axis=1) #gives sum of all elements in column(0,0)+(0,1)+(0,2)(etc)...

array([ 6, 15, 24])

In [33]:
ar.T #transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
ar.size #shows size

9

In [35]:
ar.ndim #shows dimensions

2

In [36]:
ar.flat

In [37]:
for items in ar.flat:
    print(items)

1
2
3
4
5
6
7
8
9


In [38]:
ar.nbytes

72

In [39]:
oneD = np.array([10,4,23,12])

In [40]:
oneD.argsort() #gives the index of sorted array

array([1, 0, 3, 2])

In [41]:
oneD.argmax() #gives index of maximum elemnet

2

In [42]:
oneD.argmin() #gives index of maximum elemnet

1

In [43]:
twoD = np.array([[10,40,34],[76,22,14],[56,23,45]])

In [44]:
twoD

array([[10, 40, 34],
       [76, 22, 14],
       [56, 23, 45]])

In [45]:
twoD.argmax()

3

In [46]:
twoD.argmin()

0

In [47]:
twoD.argmax(axis=0)

array([1, 0, 2])

In [48]:
twoD.argmin(axis=0)

array([0, 1, 1])

In [49]:
twoD.argmax(axis=1)

array([1, 0, 0])

In [50]:
twoD.argmin(axis=1)

array([0, 2, 1])

In [53]:
twoD

array([[10, 40, 34],
       [76, 22, 14],
       [56, 23, 45]])

In [51]:
twoD.argsort()

array([[0, 2, 1],
       [2, 1, 0],
       [1, 2, 0]])

In [63]:
twoD.argsort(axis=1)

array([[0, 2, 1],
       [2, 1, 0],
       [1, 2, 0]])

In [64]:
twoD.argsort(axis=0)

array([[0, 1, 1],
       [2, 2, 0],
       [1, 0, 2]])

In [67]:
twoD.ravel()

array([10, 40, 34, 76, 22, 14, 56, 23, 45])

In [68]:
oneD.ravel()

array([10,  4, 23, 12])

# calculation on array

In [75]:
a = np.array([[1,2],[3,4]])

In [76]:
b = np.array([[3,4],[5,6]])

In [77]:
a + b

array([[ 4,  6],
       [ 8, 10]])

In [78]:
a * b

array([[ 3,  8],
       [15, 24]])

In [81]:
root = np.array([36,25,10,9,7])

In [82]:
np.sqrt(root)

array([6.        , 5.        , 3.16227766, 3.        , 2.64575131])

In [83]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [84]:
a

array([[1, 2],
       [3, 4]])

In [86]:
a.max()

4

In [87]:
a.min()

1

In [89]:
a

array([[1, 2],
       [3, 4]])

In [88]:
a.sum()

10

In [95]:
a

array([[1, 2],
       [3, 4]])

In [97]:
a.shape

(2, 2)

In [101]:
np.where(a>2)

(array([1, 1]), array([0, 1]))